### ISSUE TITLE
DataList isn't updating on StateHasChanged

### ISSUE THREAD

**Issue by dmarciano** [akorchev/blazor.radzen.com#3]
I'm current using the DataList component to show a list of object.  It populates correctly, however if I remove an item from the collection and call StateHasChanged the DataList is not updated.  However, if I go to a different page, and then go back to the first page, the item is removed as expected.

Is there a work around to force the DataList automatically update the displayed data without having to page?

**Comment by enchev** [comment]
You can call Reload() method.
